name = "account-monitor"
account_id = "bbe7913c77b349926a3c18505196e2fd"
workers_dev = true
main = "account-monitor.js"
compatibility_date = "2024-03-22"

# Triggers to run the worker on a schedule
# Adjust the cron timing as needed
[triggers]
crons = ["*/1 * * * *"]  # This runs the worker every 15 minutes

# If you are using any KV Namespaces, define them here
# [kv_namespaces]
#   [kv_namespaces.binding]
#   id = "your_kv_namespace_id"
#   preview_id = "your_preview_kv_namespace_id"
